### PR TITLE
Add --mute-audio support

### PR DESCRIPTION
**Pull request by darlenedms**

### CODE REVIEW

**Comment by li-xinyang** [comment]
This is cool, the autoplay is truly annoying sometimes, but it could be even better if everything is done inside the headless chrome instead of via selenium.

**Comment by darlenedms** [comment]
Yeah, it would be nice... unless they block headless browsers.
It has to be tested. 🤔

**Comment by li-xinyang** [comment]
No, they had no way to block headless browser. It works exactly same as the regular Chrome browser and we can always set the `user-agent`. Thanks again for the PR @darlenedms, good work.

**Comment by darlenedms** [comment]
This post http://antoinevastel.github.io/bot%20detection/2017/08/05/detect-chrome-headless.html explains other ways to detect headless browsers beyond user-agent but I guess few sites does that anyways.
Thanks! 😄

**Comment by li-xinyang** [comment]
I glanced the post and all these things cannot detect headless Chrome and they cannot be definite that we are using a headless browser (only "maybe"). 😄

**Pull request merged**
